### ISSUE TITLE
fsturb roadmap

### ISSUE THREAD

**Issue by apatlpo** [slgentil/croco#12]
List of items to address with fsturb configuration:

- [ ] check forcing on density works for a purely barotropic forcing

- [ ] modulate forcing amplitude

- [ ] figure out if relaxation needs to be turned back on

- [ ] implement simple movie generator and make pretty movies

- [ ] implement modal decomposition of the flow and modal energy temporal evolution 

- [ ] implement atmospheric forcing for NIW generation

- [ ] turn internal tide back on and adjust sponge layers
